---
- hosts: local
  remote_user: root
  gather_facts: False
  tasks:
    - name: install vsftpd
      yum: pkg=vsftpd state=latest

    - debug:
        msg: "config the vsftpd.conf file"
    - template:
        src: vsftpd.conf.j2
        dest: /etc/vsftpd/vsftpd.conf
        owner: root
        group: root
        mode: '0600'
        backup: yes

    - debug:
        msg: "install & config & start vsftpd"
    - service:
        name: vsftpd
        enabled: yes
        state: started
    - debug:
        msg: "stop firewalld"
    - service:
        name: firewalld
        enabled: no
        state: stopped
