parameter_defaults:
  CinderBackupBackend: ceph 
  CephAnsibleDisksConfig: 
    osd_scenario: collocated
    dmcrypt: true
    devices:
      - /dev/sdb
  ControllerCount: 1
  OvercloudControlFlavor: control
  ComputeCount: 0
  OvercloudComputeFlavor: compute
  CephStorageCount: 0
  OvercloudCephStorageFlavor: ceph-storage
  CephMonCount: 0 
  OvercloudCephMonFlavor: ceph-mon
  CephMdsCount: 0
  OvercloudCephMdsFlavor: ceph-mds
  ComputeHCICount: 3
  OvercloudComputeHCIFlavor: osdcompute
  NeutronNetworkType: vlan
